language: csharp
solution: mockresponse.sln
mono: none
dotnet: 2.0.0
services:
  - docker
script:
  - dotnet restore mockresponse.sln
  - dotnet build -c c-configuration mockresponse.sln
before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t $DOCKER_USERNAME/mockresponse ./MockResponse.Api;
    docker push $DOCKER_USERNAME/mockresponse;
    fi
