language: csharp
solution: mockresponse.sln
mono: none
dotnet: 2.0.0
services:
  - docker
before_install:
  - dotnet restore mockresponse.sln
  - dotnet publish ./MockResponse.Api/MockResponse.Api.csproj -c c-configuration -o ./obj/Docker/publish
  - dotnet publish ./MockResponse.Web/MockResponse.Web.csproj -c c-configuration -o ./obj/Docker/publish
install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t $DOCKER_USERNAME/mockresponse.api ./MockResponse.Api;
    docker push $DOCKER_USERNAME/mockresponse.api;
    fi
