version: '2'

services:
  mockresponse.api:
    image: mockresponse.api
    build:
      context: ./api
      dockerfile: Dockerfile

  mockresponse.web:
    image: mockresponse.web
    build:
      context: ./MockResponse
      dockerfile: Dockerfile