version: '3'

services:
  mockresponse.api:
    image: mockresponse.api
    build:
      context: ./MockResponse.Api
      dockerfile: Dockerfile

  mockresponse.web:
    image: mockresponse.web
    build:
      context: ./MockResponse.Web
      dockerfile: Dockerfile
  
  # reverse-proxy:
  #  build: ./nginx
  #  container_name: mockresponse_hosting
  #  ports:
  #    - "80:80"