version: '2'

services:
  mockresponse.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  mockresponse.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
