version: '2'
services:
  mockresponse-app:
    container_name: mockresponse_site
    build: ./dotnet
    

  reverse-proxy:
    build: ./nginx
    container_name: mockresponse_hosting
    ports:
      - "1111:1111"
  