version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./mockresponse.sln && dotnet publish ./mockresponse.sln -c Release -o ./obj/Docker/publish"
