version: '3'

services:
  mockresponse.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  mockresponse.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
