version: '2'

services:
  mockresponse.api:
    image: mockresponse.api
    build:
      context: ./MockResponse.Api
      dockerfile: Dockerfile

  mockresponse.web:
    image: mockresponse.web
    build:
      context: ./MockResponse.Web
      dockerfile: Dockerfile