FROM microsoft/dotnet:latest

# Create directory for the app source code
RUN mkdir -p /usr/src/mockresponse
WORKDIR /usr/src/mockresponse

# Copy the source and restore dependencies
COPY . /usr/src/mockresponse
RUN dotnet restore

# Expose the port and start the app
EXPOSE 5001
CMD [ "dotnet", "run", "--environment", "Production", "--server.urls", "http://*:5001" ]